Repository keycloak/keycloak-operator, pull requests merged in 2020-08, with the labels that each got.

#108 KEYCLOAK-12273 Keycloak Operator documentation
  README.md
  docs/README.asciidoc
  docs/backups.asciidoc
  docs/building.md
  docs/external-database.asciidoc
  docs/keycloak-client.asciidoc
  docs/keycloak-user.asciidoc
Labels: component/docs, priority/critical

#229 KEYCLOAK-14316 Fix "assignment to entry in nil map" error
  pkg/model/client_secret.go
  pkg/model/database_secret.go
  pkg/model/database_secret_test.go
  pkg/model/keycloak_admin_secret.go
Labels: status/in-review

#236 OLM sync
  deploy/olm-catalog/keycloak-operator/11.0.0/keycloak-operator.v11.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/keycloak-operator/11.0.0/keycloakbackups.keycloak.org.crd.yaml
  deploy/olm-catalog/keycloak-operator/11.0.0/keycloakclients.keycloak.org.crd.yaml
  deploy/olm-catalog/keycloak-operator/11.0.0/keycloakrealms.keycloak.org.crd.yaml
  deploy/olm-catalog/keycloak-operator/11.0.0/keycloaks.keycloak.org.crd.yaml
  deploy/olm-catalog/keycloak-operator/11.0.0/keycloakusers.keycloak.org.crd.yaml
  deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
Labels: status/ready

#243 INTLY-8357 Pod monitor removal
  deploy/cluster_roles/cluster_role.yaml
  deploy/role.yaml
  pkg/common/auto_detect.go
  pkg/common/cluster_state.go
  pkg/controller/keycloak/keycloak_controller.go
  pkg/controller/keycloak/keycloak_reconciler.go
  pkg/model/constants.go
  pkg/model/pod_monitor.go
Labels: kind/enhancement, status/in-review
