Repository keycloak/keycloak-operator, pull requests merged in 2020-07, with the labels that each got.

#212 KEYCLOAK-14518 CRD cleanup
  deploy/crds/keycloak.org_keycloakbackups_crd.yaml
  deploy/crds/keycloak.org_keycloakclients_crd.yaml
  deploy/crds/keycloak.org_keycloakrealms_crd.yaml
  deploy/crds/keycloak.org_keycloaks_crd.yaml
  deploy/crds/keycloak.org_keycloakusers_crd.yaml
  pkg/apis/keycloak/api_test.go
  pkg/apis/keycloak/v1alpha1/keycloak_types.go
  pkg/apis/keycloak/v1alpha1/keycloakbackup_types.go
  pkg/apis/keycloak/v1alpha1/keycloakclient_types.go
  pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  pkg/apis/keycloak/v1alpha1/keycloakuser_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
Labels: kind/enhancement, priority/important, status/in-review

#216 KEYCLOAK-13112 Fixed client generation error and ImplicitFlow
  pkg/apis/keycloak/v1alpha1/keycloakclient_types.go
  pkg/common/cluster_actions.go
  pkg/controller/keycloakclient/keycloakrclient_reconciler.go
Labels: kind/bug

#220 KEYCLOAK-14327 Allow user to specify storage class
  deploy/crds/keycloak.org_keycloakbackups_crd.yaml
  deploy/crds/keycloak.org_keycloaks_crd.yaml
  pkg/apis/keycloak/v1alpha1/keycloak_types.go
  pkg/apis/keycloak/v1alpha1/keycloakbackup_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  pkg/common/cluster_state.go
  pkg/controller/keycloak/keycloak_migrations.go
  pkg/controller/keycloak/keycloak_reconciler.go
  pkg/model/postgresql_backup_persistent_volume_claim.go
  pkg/model/postgresql_persistent_volume_claim.go
Labels: area/storage, kind/enhancement, missing/tests, status/hold
