Repository keycloak/keycloak-operator, pull requests merged in 2020-10, with the labels that each got.

#241 KEYCLOAK-15014 Add scopes to realm and client
  deploy/crds/keycloak.org_keycloakclients_crd.yaml
  deploy/crds/keycloak.org_keycloakrealms_crd.yaml
  pkg/apis/keycloak/v1alpha1/keycloakclient_types.go
  pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  test/e2e/keycloak_client_test.go
  test/e2e/keycloak_realm_test.go
Labels: kind/enhancement, status/in-review, status/needs-rebase

#247 KEYCLOAK-15476: Support external keycloak instances
  deploy/crds/keycloak.org_keycloakrealms_crd.yaml
  deploy/crds/keycloak.org_keycloaks_crd.yaml
  deploy/examples/keycloak/external-keycloak.yaml
  pkg/apis/keycloak/v1alpha1/keycloak_types.go
  pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  pkg/common/client.go
  pkg/common/cluster_state.go
  pkg/controller/keycloak/keycloak_controller.go
  pkg/controller/keycloakbackup/keycloakbackup_controller.go
  pkg/controller/keycloakclient/keycloakclient_controller.go
  pkg/controller/keycloakclient/keycloakclient_reconciler.go
  pkg/controller/keycloakrealm/keycloakrealm_controller.go
  pkg/controller/keycloakuser/keycloakuser_controller.go
  test/e2e/constants.go
  test/e2e/keycloak_client_test.go
  test/e2e/keycloak_main_test.go
  test/e2e/keycloak_realm_test.go
  test/e2e/keycloaks_test.go
  test/e2e/utils.go
Labels: kind/feature, status/in-review

#255 KEYCLOAK-14782 KEYCLOAK-14470 KEYCLOAK-12677 Custom Configuration
  deploy/crds/keycloak.org_keycloaks_crd.yaml
  deploy/examples/keycloak/keycloak-with-experimental-settings.yaml
  go.sum
  pkg/apis/keycloak/v1alpha1/keycloak_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  pkg/controller/keycloak/keycloak_reconciler_test.go
  pkg/model/keycloak_deployment.go
  pkg/model/keycloak_deployment_test.go
  pkg/model/rhsso_deployment.go
  pkg/model/rhsso_deployment_test.go
  pkg/model/util.go
  pkg/model/util_test.go
Labels: kind/feature, priority/critical
