Repository keycloak/keycloak-operator, pull requests merged in 2021-11, with the labels that each got.

#387 KEYCLOAK-19086 Default Client Roles are not implicitly created
  deploy/crds/keycloak.org_keycloakrealms_crd.yaml
  deploy/examples/client/client-secret.yaml
  pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  pkg/common/client.go
  pkg/common/client_state.go
  pkg/common/cluster_actions.go
  pkg/controller/keycloakclient/keycloakclient_reconciler.go
  test/e2e/keycloak_client_test.go
Labels: status/ready

#384 KEYCLOAK-19503 escape name of the secret for client
  pkg/common/client.go
  pkg/controller/keycloakclient/keycloakclient_reconciler_test.go
  pkg/model/client_secret.go
  pkg/model/util.go
Labels: status/requires-discussion

#366 Updating user mailing list link
  README.md
Labels: missing/jira
