Repository keycloak/keycloak-operator, pull requests merged in 2021-10, with the labels that each got.

#362 KEYCLOAK-18867 change getDesiredUserSate to getDesiredUserState
  pkg/controller/keycloakrealm/keycloakrealm_reconciler.go
Labels: status/ready

#360 Typo
  Makefile
Labels: status/in-review

#372 KEYCLOAK-19061 doc: add reference to KeycloakUser CRD
  README.md
Labels: missing/jira
